import type { CategoryId } from "@/lib/categories";

export interface Product {
  id: string;
  categoryId: CategoryId;
  title: string;
  description: string;
  materials: string;
  size: string;
  price: string;
  image: string;
  order: string;
}

// Edit each product individually below.
export const PRODUCTS: Product[] = [
  {
    id: "1",
    categoryId: "toys",
    title: "Наименование товара 1",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_1.jpg",
  },
  {
    id: "2",
    categoryId: "toys",
    title: "Наименование товара 2",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_2.jpg",
  },
  {
    id: "3",
    categoryId: "toys",
    title: "Наименование товара 3",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_3.jpg",
  },
  {
    id: "4",
    categoryId: "toys",
    title: "Наименование товара 4",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_4.jpg",
  },
  {
    id: "5",
    categoryId: "toys",
    title: "Наименование товара 5",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_5.jpg",
  },
  {
    id: "6",
    categoryId: "toys",
    title: "Наименование товара 6",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_6.jpg",
  },
  {
    id: "7",
    categoryId: "toys",
    title: "Наименование товара 7",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_7.jpg",
  },
  {
    id: "8",
    categoryId: "toys",
    title: "Наименование товара 8",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_8.jpg",
  },
  {
    id: "9",
    categoryId: "toys",
    title: "Наименование товара 9",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_9.jpg",
  },
  {
    id: "10",
    categoryId: "toys",
    title: "Наименование товара 10",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_10.jpg",
  },
  {
    id: "11",
    categoryId: "toys",
    title: "Наименование товара 11",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_11.jpg",
  },
  {
    id: "12",
    categoryId: "toys",
    title: "Наименование товара 12",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/toy_12.jpg",
  },
  {
  id: "13",
  categoryId: "bags",
  title: "Каталея",
  description: `Сумочка в технике ирландского кружева
  Застегивается на магнитную кнопку. Опционально дополняется подкладом и плечевым ремешком.`,
  materials: "Материалы: полиэфирный шнур, кожа, шерсть / акрил",
  size: `Параметры: высота 20 см (без учёта ручек), 12 см × 26 см`,
  price: "12 000 ₽",
  order: "Под заказ в любом цвете пряжи и фурнитуры",
  image: "/images/bag_1.jpg",
},
  {
    id: "14",
    categoryId: "bags",
    title: "Этель",
    description: `Сумочка-цветок
    Застегивается на магнитную кнопку. Опционально дополняется подкладом-мешочком и плечевым ремешком.`,
    materials: "Материалы: полиэфирный шнур",
    size: "Параметры: высота 31 см, диаметр 20 см, глубина 7-8 см",
    price: "6 000 ₽",
    order: "Под заказ в любом цвете пряжи и фурнитуры",
    image: "/images/bag_2.jpg",
  },
  {
    id: "15",
    categoryId: "bags",
    title: "Ребекка",
    description: `Сумочка кросс-боди
    Застёжка – портфельный замок. Опционально дополняется подкладом, декорируется брошью или обвесом.`,
    materials: "Материалы: полиэфирный шнур, кожа",
    size: "Параметры: высота 20 см, ширина 22 см, глубина 10 см",
    price: "5 500 ₽",
    order: "Под заказ в любом цвете пряжи и фурнитуры",
    image: "/images/bag_3.jpg",
  },
  {
    id: "16",
    categoryId: "bags",
    title: "Катюша",
    description: "Клатч в винтажном стиле. Застёжка – портфельный замок. Опционально дополняется подкладом. ",
    materials: "Материалы: полиэфирный шнур",
    size: "Параметры: высота 14 см, ширина 22 см, глубина 7 см. Два отделения",
    order: "Под заказ в любом цвете пряжи и фурнитуры",
    price: "5 500 ₽",
    image: "/images/bag_4.jpg",
  },
  {
    id: "17",
    categoryId: "bags",
    title: "Магнолия",
    description: "Сумка-шоппер, пляжная сумка. Опционально дополняется обвесом.",
    materials: "Материалы: полиэфирный шнур, кожа",
    size: "Параметры: высота 30 см, ширина 30 см. Ручки 56 см",
    order: "Под заказ в любом цвете пряжи и фурнитуры",
    price: "4 500 ₽",
    image: "/images/bag_5.jpg",
  },
  {
    id: "18",
    categoryId: "sets",
    title: "Наименование товара 18",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_1.jpg",
  },
  {
    id: "19",
    categoryId: "sets",
    title: "Наименование товара 19",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_2.jpg",
  },
  {
    id: "20",
    categoryId: "sets",
    title: "Наименование товара 20",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_3.jpg",
  },
  {
    id: "21",
    categoryId: "sets",
    title: "Наименование товара 21",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_4.jpg",
  },
  {
    id: "22",
    categoryId: "sets",
    title: "Наименование товара 22",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_5.jpg",
  },
  {
    id: "23",
    categoryId: "sets",
    title: "Наименование товара 23",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_6.jpg",
  },
  {
    id: "24",
    categoryId: "sets",
    title: "Наименование товара 24",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/set_7.jpg",
  },
  {
    id: "25",
    categoryId: "baskets",
    title: "Наименование товара 25",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_1.jpg",
  },
  {
    id: "26",
    categoryId: "baskets",
    title: "Наименование товара 26",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_2.jpg",
  },
  {
    id: "27",
    categoryId: "baskets",
    title: "Наименование товара 27",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_3.jpg",
  },
  {
    id: "28",
    categoryId: "baskets",
    title: "Наименование товара 28",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_4.jpg",
  },
  {
    id: "29",
    categoryId: "baskets",
    title: "Наименование товара 29",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_5.jpg",
  },
  {
    id: "30",
    categoryId: "baskets",
    title: "Наименование товара 30",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_6.jpg",
  },
  {
    id: "31",
    categoryId: "baskets",
    title: "Наименование товара 31",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_7.jpg",
  },
  {
    id: "32",
    categoryId: "baskets",
    title: "Наименование товара 32",
    description: "Краткое описание товара и его особенностей...",
    materials: "Материалы: Натуральное дерево, текстиль",
    size: "Размер: 120 × 80 × 75 см",
    price: "15 000 ₽",
    image: "/images/basket_8.jpg",
  },
];

export function getCategoryProducts(categoryId: CategoryId): Product[] {
  return PRODUCTS.filter((product) => product.categoryId === categoryId);
}
